[package]
name = "cdwe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version="4.3.12", features=["derive"] }
serde = {version = "1.0.171", features = ["derive"]}
toml = "0.7.6"
